name: protoTyper
services:
  frontend:
    container-name: protoTyper-front-prod
    build:
      context: ../
      target: production
    restart: always
    image: protoTyper-frontend:1.0
    env_file:
      - ../.env
    ports:
      - "3000:80"